# Generated by Django 4.1 on 2022-10-14 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Niveau",
            fields=[
                ("idNiveau", models.AutoField(primary_key=True, serialize=False)),
                ("niveau", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                ("idClasse", models.AutoField(primary_key=True, serialize=False)),
                ("libelleSalle", models.CharField(max_length=15)),
                ("montant", models.FloatField()),
                (
                    "niveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Classe.niveau"
                    ),
                ),
            ],
        ),
    ]
