# Generated by Django 4.1 on 2022-10-14 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Personnel", "0001_initial"),
        ("Classe", "0001_initial"),
        ("Apprenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("idMatiere", models.AutoField(primary_key=True, serialize=False)),
                ("nomMatiere", models.CharField(max_length=45)),
                ("coefficient", models.FloatField()),
                ("description", models.TextField(default="Ici la description...")),
                (
                    "idNiveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Classe.niveau"
                    ),
                ),
                (
                    "idProf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Personnel.enseignant",
                    ),
                ),
                (
                    "idpersonne",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Apprenant.eleve",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("idNote", models.AutoField(primary_key=True, serialize=False)),
                ("note", models.FloatField()),
                (
                    "idApprenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Apprenant.eleve",
                    ),
                ),
                (
                    "idMatiere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matiere.subject",
                    ),
                ),
            ],
        ),
    ]
