# Generated by Django 4.1 on 2022-10-14 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Classe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eleve",
            fields=[
                ("idApprenant", models.AutoField(primary_key=True, serialize=False)),
                ("nomApprenant", models.CharField(blank=True, max_length=50)),
                ("dateNaissance", models.DateField(blank=True, null=True)),
                ("dateInscription", models.DateField()),
                (
                    "photo_profil",
                    models.ImageField(default="blank.png", upload_to="Images"),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("Garçon", "Garçon"), ("Fille", "Fille")],
                        max_length=10,
                    ),
                ),
                ("totalPaye", models.FloatField()),
                (
                    "idClasse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Classe.classe"
                    ),
                ),
            ],
        ),
    ]
